### ISSUE TITLE
Suggestion: Automated Travis Docker images

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/faas-o6s#5]
## Suggestion

Automated Travis Docker images

- [ ] CI for building the image using Docker
- [ ] Automatic pushing of image tags with GitHub releases

**Comment by alexellis** [comment]
@stefanprodan is this done now?

**Comment by stefanprodan** [comment]
take a look at https://github.com/openfaas-incubator/faas-o6s/blob/master/.travis.yml

**Comment by alexellis** [comment]
So can we close the issue?

**Comment by stefanprodan** [comment]
Have you setup Travis?

**Comment by alexellis** [comment]
I'll add the config later today. I thought this was done already

**Comment by stefanprodan** [comment]
This can be closed

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
You should be able to use Derek to manage these issues / PRs. It may take 5 mins for the CDN cache to clear as I didn't see a .DEREK.yml file in the repo and created one now.
